### PR TITLE
go 1.22+ support

### PR DESCRIPTION
**Pull request by grosser**
fixes https://github.com/julz/importas/issues/21

### CODE REVIEW

**Comment by grosser** [comment]
@julz can you check this PR ?

**Comment by julz** [comment]
thanks, looks like github actions has some complaints tho 🤔

**Comment by grosser** [comment]
welp need another approval 😞

**Comment by grosser** [comment]
idk how this is supposed :/
... `go 1.22.0` is invalid for 1.20
but `go 1.22` is invalid for 1.22 🫨

**Comment by grosser** [comment]
got it now 🤞 
... can't use latest version of the tools because they need >1.22

**Comment by julz** [comment]
awesome looks good now, thank you!

**Pull request merged**
